### ISSUE TITLE
Update to spring 2020 courses

### ISSUE THREAD

**Issue by jamesbond007325** [miguelHx/bobcat-courses#37]
I was interesting in trying to update the code to work with the 2020 courses, but there a 6 digit number associated with each term that I’m just not sure we’re you get them from? I would really appreciate it if you could help me figure out were you get the value from? Thank you so much! Loved using this code the past semesters!

**Comment by miguelHx** [comment]
Updated now in most recent commit https://github.com/miguelHx/bobcat-courses/commit/46ce29f22c25258379ddf9517f71283c143e2c84.  Thanks for your comment.  FYI, the 6 digit number is obtained from the HTML form in the "select term" page on the UCM registrar website.

**Comment by miguelHx** [comment]
@jamesbond007325 make sure you refresh the page a few times if it doesn't update.
